### ISSUE TITLE
urlman.py is not included in the distro under 2.0

### ISSUE THREAD

**Issue by jefftriplett** [andrewgodwin/urlman#14]
This is going to sound weird, but when I upgrade to 2.0 I get: 

```shell
ModuleNotFoundError: No module named 'urlman'
```

```shell
❯ ls -la ../../lib/python3.9/site-packages/urlman*
total 64
drwxr-xr-x    9 jefftriplett  staff    288 Jun 10 19:47 .
drwxr-xr-x  239 jefftriplett  staff   7648 Jun 10 19:47 ..
-rw-r--r--    1 jefftriplett  staff      4 Jun 10 19:47 INSTALLER
-rw-r--r--    1 jefftriplett  staff  10172 Jun 10 19:47 LICENSE
-rw-r--r--    1 jefftriplett  staff   3354 Jun 10 19:47 METADATA
-rw-r--r--    1 jefftriplett  staff    561 Jun 10 19:47 RECORD
-rw-r--r--    1 jefftriplett  staff      0 Jun 10 19:47 REQUESTED
-rw-r--r--    1 jefftriplett  staff    110 Jun 10 19:47 WHEEL
-rw-r--r--    1 jefftriplett  staff      7 Jun 10 19:47 top_level.txt
```

When I downgrade to 1.4, an `urlman.py` file is here as expected. Since you switched from a one-file distro to a folder + few files, I suspect something needed up dates in setup.py to include it.

**Comment by andrewgodwin** [comment]
This is what I get for using a new build process. I'll get it fixed and do a new release.

**Comment by andrewgodwin** [comment]
Alright, 2.0.1 should fix this - it was the switch from a module to a package that did it!

**Comment by jefftriplett** [comment]
Thank you. I can confirm that it's working for me.

**Comment by rixx** [comment]
Ugh sorry, I was afraid of something like this, but testing with the dev install didn't show it. (Naturally, but I didn't think that far)

**Comment by andrewgodwin** [comment]
No worries - the build module _did_ print out warnings that was no code in what it was building, but I apparently ignored them :)

**Comment by tacerus** [comment]
Could you create a tag for 2.0.1 as well? I maintain a distribution package and want to avoid having to build from master.

**Comment by andrewgodwin** [comment]
@tacerus Done!

**Comment by tacerus** [comment]
Much appreciated, thank you!
