### ISSUE TITLE
Add inheritance and composition to urls classes

### ISSUE THREAD

**Issue by bluesurfer** [andrewgodwin/urlman#15]
It appears that the library does not support inheritance between `urls` classes. I don't know if it is intended or actually a bug.

Consider the following models:

```
class Person(models.Model):
    class urls(urlman.Urls):
        update = '/persons/{self.pk}/update/'


class Student(models.Model):
    class Meta:
        proxy = True

    class urls(Person.urls):
        update = '/students/{self.pk}/update/'

```

That would cause a `ValueError: No URL called '__mro_entries__' on 'NoneType'`.

**Comment by andrewgodwin** [comment]
Inheritance in this sense was never intended.
