### ISSUE TITLE
Provide a way to use full url with https/domain in a template.

### ISSUE THREAD

**Issue by apollo13** [andrewgodwin/urlman#4]
One usecase for using full URLs are usually email templates. In those I'd obviously like to use https since everything on my site uses https. Any ideas on how to approach that? A filter would be doable but given that URLs are usually all http or https (aside from some weird exceptions maybe), I think a setting to control the defaults would be the best way to go. 

That said, passing in the request object might be another way to create a full URL with the proper domain names etc (but would still require a filter).

**Comment by andrewgodwin** [comment]
Yes, I'm not sure about what the best way of controlling settings like that is. I don't really want to bring in the Django settings system if I can help it, since the project doesn't use anything like it right now, but there aren't many options; the only other idea that comes to mind is a context manager, like this:

```
with urls.defaults(hostname="aeracode.org", scheme="https"):
   ...
```

This could then easily be put into a Django middleware if desired, too. It would, annoyingly, have to use threadlocals to track the state.

**Comment by apollo13** [comment]
Jupp, all the options sound somewhat annoying :( But that is more an issue with Django itself.

**Comment by rixx** [comment]
I would welcome something like that (because I've recently forgotten to set the hostname in multiple places … yeah.). Would an optional usage of the django settings system be doable? Trying to get defaults from `django.conf.settings` and using `''` and `'localhost'` on failure doesn't seem too bad?

**Comment by andrewgodwin** [comment]
I think it would be sensible enough, as long as the failure mode is nice. I wonder if there is a way to turn the mode on (class variable?) and give explicit errors rather than soft-failing to `''` etc.

**Comment by rixx** [comment]
Oh, speaking of class variables – what do you think of a `get_hostname()`, `get_scheme()` etc on the Url class that a user may implement, and that returns the current default values otherwise? This would do nicely for me and may be one of the more flexible and readable options.

**Comment by andrewgodwin** [comment]
Totally OK with that too. Maybe that, and provide a DjangoUrls subclass that populates them with settings by default or something?

**Comment by rixx** [comment]
I could prepare a PR, if that's fine by you?

**Comment by andrewgodwin** [comment]
Absolutely!
