### ISSUE TITLE
Use CamelCase for 'urls' class name

### ISSUE THREAD

**Issue by bluesurfer** [andrewgodwin/urlman#7]
First of all, let me say that this library is awesome! Why only 48 stars?
It should be included in core Django 😄

Anyway, I would like to know why the class 'urls' doesn't respect PEP 8 style guide (it should be in CamelCase). 

What if the metaclass name becomes `MetaUrls`? Of course one must still have access to `object.urls` in the template but that should not be a problem.

**Comment by andrewgodwin** [comment]
The class is called `Urls`, I don't see any problem. The one you assign to a model is called `urls`, sure, but that's an attribute, so it still fits.
